config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  # Defines the root path route ("/")
  # root "posts#index"
  root "home#index"
  resources :trips
  resources :cars
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/car.rb
class Car < ApplicationRecord
  has_many :trips, dependent: :destroy

  validates :brand, presence: true
  validates :model, presence: true
  validates :model, presence: true
end

app/models/trip.rb
class Trip < ApplicationRecord
  belongs_to :user
  belongs_to :car

  validates :from, presence: true
  validates :distance, presence: true
  validates :to, presence: true
  validates :date_beginning, presence: true
  validates :date_end, presence: true

  validate :car_not_already_booked
  validate :valid_end_date

  private
  def car_not_already_booked
    overlapping_trips = Trip.where(car_id: car_id)
                            .where.not(id: id)
                            .where('date_beginning <= ? AND date_end >= ?', date_end, date_beginning)
    if overlapping_trips.exists?
      errors.add(:car_id, 'is already booked in this period')
    end
  end

  def valid_end_date
    if date_end < date_beginning
      errors.add(:date_end, 'must comes after or be equal to beginning date')
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :trips, dependent: :destroy

  enum role: { normal: 0, boss: 1, admin: 2 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pagy::Backend
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController

  before_action :find_car, only: [:show, :destroy, :edit, :update]

  def index
    @pagy, @cars = pagy(Car.all)
  end

  def destroy
    if @car.destroy
      flash[:notice] = 'Car deleted successfully'
    else
      flash[:notice] = @car.errors.full_messages.join(", ")
    end
    redirect_to cars_path
  end

  def show
  end

  def edit
  end

  def new
    @car = Car.new
  end

  def update
    if @car.update(car_params)
      flash[:notice] = 'Car updated successfully'
      redirect_to car_path(@car)
    else
      respond_to do |format|
        format.html { render :new, status: :unprocessable_entity }
        format.turbo_stream {render turbo_stream: turbo_stream.replace('cars_feedback', partial: 'cars_feedback', locals: { car: @car })}
      end
    end
  end

  def create
    @car = Car.new(car_params)
    if @car.save
      flash[:notice] = 'Car created successfully'
      redirect_to car_path(@car)
    else
      respond_to do |format|
        format.html { render :new, status: :unprocessable_entity }
        format.turbo_stream {render turbo_stream: turbo_stream.replace('cars_feedback', partial: 'cars_feedback', locals: { car: @car })}
      end
    end
  end

  def find_car
    @car = Car.find_by id: params[:id]
    unless @car
      flash[:notice] = "Car not found"
      redirect_to cars_path
    end
  end

  def car_params
    params.require(:car).permit(:brand, :model, :picture, :run, :fuel_consumption)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

end

app/controllers/trips_controller.rb
class TripsController < ApplicationController

  before_action :find_trip, only: [:show, :destroy, :edit, :update]
  def index
    @pagy, @trips = pagy(Trip.all)
  end

  def show
  end

  def destroy
    if @trip.destroy
      flash[:notice] = 'Trip deleted successfully'
    else
      flash[:notice] = @trip.errors.full_messages.join(", ")
    end
    redirect_to trips_path
  end

  def edit
  end

  def new
    @trip = Trip.new
  end

  def update
      if @trip.update(trip_params)
        flash[:notice] = 'Trip updated successfully'
        redirect_to trip_path(@trip)
      else
        respond_to do |format|
          format.html { render :new, status: :unprocessable_entity }
          format.turbo_stream {render turbo_stream: turbo_stream.replace('trips_feedback', partial: 'trips_feedback', locals: { trip: @trip })}
        end
      end
  end

  def create
    @trip = Trip.new(trip_params)
    if @trip.save
      flash[:notice] = 'Trip created successfully'
      redirect_to trip_path(@trip)
    else
      respond_to do |format|
        format.html { render :new, status: :unprocessable_entity }
        format.turbo_stream {render turbo_stream: turbo_stream.replace('trips_feedback', partial: 'trips_feedback', locals: { trip: @trip })}
      end
    end
  end

  def find_trip
    @trip = Trip.find_by id: params[:id]
    unless @trip
      flash[:notice] = "Trip not found"
      redirect_to trips_path
    end
  end

  def trip_params
    params.require(:trip).permit(:from, :to, :pitstop, :distance, :date_beginning, :date_end, :user_id, :car_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController


  before_action :find_user, only: [:show, :destroy, :edit, :update]
  def index
    @pagy, @users = pagy(User.all)
  end

  def show
  end

  def destroy
    if @user.destroy
      flash[:notice] = 'User deleted successfully'
    else
      flash[:notice] = @user.errors.full_messages.join(", ")
    end
    redirect_to users_path
  end

  def edit
  end

  def new
    @user = User.new
  end

  def update
    if @user.update(user_params)
      flash[:notice] = 'User updated successfully'
      redirect_to user_path(@user)
    else
      respond_to do |format|
        format.html { render :new, status: :unprocessable_entity }
        format.turbo_stream {render turbo_stream: turbo_stream.replace('users_feedback', partial: 'users_feedback', locals: { user: @user })}
      end
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = 'User created successfully'
      redirect_to user_path(@user)
    else
      respond_to do |format|
        format.html { render :new, status: :unprocessable_entity }
        format.turbo_stream {render turbo_stream: turbo_stream.replace('users_feedback', partial: 'users_feedback', locals: { user: @user })}
      end
    end
  end

  def find_user
    @user = User.find_by id: params[:id]
    unless @user
      flash[:notice] = "User not found"
      redirect_to users_path
    end
  end

  def user_params
    params.require(:user).permit(:email, :password, :first_name, :last_name, :role)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cars/_cars_feedback.html.erb
<% if @car.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@car.errors.count, "error") %> prohibited this car from being saved:</h2>
    <ul>
      <% @car.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/cars/edit.html.erb
<%= form_for @car, html: { class: "form-horizontal container mt-5" }, data: { turbo_frame: :_top } do |form|%>

  <%= turbo_frame_tag "cars_feedback" do %>
    <%= render "cars_feedback" %>
  <% end %>

  <div class="form-group">
    <%= form.label :brand, class: "control-label" %>
    <%= form.text_field :brand, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :model, class: "control-label" %>
    <%= form.text_field :model, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :picture, class: "control-label" %>
    <%= form.text_field :picture, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :run, class: "control-label" %>
    <%= form.number_field :run, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :fuel_consumption, class: "control-label" %>
    <%= form.number_field :fuel_consumption, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.submit "Save", class: "btn btn-primary" %>
  </div>
<% end %>
<%= link_to 'Back', cars_path, class: "btn btn-primary mt-3 m-2" %>

app/views/cars/index.html.erb
<div class="container mt-5">
  <%== pagy_nav @pagy %>
  <table class="table">
    <thead>
    <tr>
      <th>Brand</th>
      <th>Model</th>
      <th>Run</th>
      <th>Fuel Consumption</th>
      <th>Actions</th>
    </tr>
    </thead>
    <tbody>
    <% @cars.each do |car| %>
      <tr>
        <td><%= car.brand %></td>
        <td><%= car.model %></td>
        <td><%= car.run %></td>
        <td><%= car.fuel_consumption %></td>
        <td>
          <%= link_to 'Edit', edit_car_path(car.id), class: 'btn btn-primary btn-sm' %>
          <%= link_to 'Delete', car_path(car.id), data: { turbo_confirm: 'Are you sure?', turbo_method: :delete}, class: 'btn btn-danger btn-sm' %>
          <%= link_to 'Details', car_path(car.id), class: 'btn btn-info btn-sm' %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
  <%= link_to 'Add Car', new_car_path, class: 'btn btn-info btn-sm' %>
</div>

app/views/cars/new.html.erb
<%= form_for @car, html: { class: "form-horizontal container mt-5" }, data: { turbo_frame: :_top } do |form|%>

  <%= turbo_frame_tag "cars_feedback" do %>
    <%= render "cars_feedback" %>
  <% end %>

  <div class="form-group">
    <%= form.label :brand, class: "control-label" %>
    <%= form.text_field :brand, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :model, class: "control-label" %>
    <%= form.text_field :model, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :picture, class: "control-label" %>
    <%= form.text_field :picture, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :run, class: "control-label" %>
    <%= form.number_field :run, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :fuel_consumption, class: "control-label" %>
    <%= form.number_field :fuel_consumption, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.submit "Save", class: "btn btn-primary" %>
  </div>
<% end %>
<%= link_to 'Back', cars_path, class: "btn btn-primary mt-3 m-2" %>

app/views/cars/show.html.erb
<div class="container mt-3">
  <h1>Details of the car</h1>
  <div class="card">
    <div class="card-body">
      <p><strong>Brand:</strong> <%= @car.brand %></p>
      <p><strong>Model:</strong> <%= @car.model %></p>
      <p><strong>run:</strong> <%= @car.run %></p>
      <p><strong>Fuel consumption:</strong> <%= @car.fuel_consumption %></p>
      <p><strong>Created At:</strong> <%= @car.created_at.strftime("%d-%m-%Y %H:%M") %></p>
      <p><strong>picture:</strong> <%= @car.picture %></p>
    </div>
  </div>

  <%= link_to 'Back', cars_path, class: "btn btn-primary mt-3" %>
</div>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid border-bottom border-primary">
    <a class="navbar-brand" href="#">FleetRider</a>
    <div class="d-flex">
      <a class="nav-link" href="<%# root_path %>">Login</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ms-auto start-0">
          <li class="nav-item dropdown ">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Menu
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li><a class="dropdown-item" href="#">Show trips</a></li>
              <li><a class="dropdown-item" href="#">Add trip</a></li>
              <li><a class="dropdown-item" href="#">Add car</a></li>
            </ul>
          </li>
        </ul>
      </div>
    </div>
  </div>
</nav>

app/views/home/index.html.erb
<section class="d-flex justify-content-center align-items-center gap-3">
  <div>
    <h2>Welcome to Fleet Rider!</h2>
    <h4>Your partner in menagmnet with fleet of cars</h4>
  </div>
  <img src="modern-car-isolated_23-2151504570.jpg" alt="car image" class="w-25">
</section>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid border-bottom border-primary">
    <a class="navbar-brand" href="/<%# root_url %>">FleetRider</a>
    <div class="d-flex">
      <a class="nav-link" href="#">Login</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ms-auto start-0">
          <li class="nav-item dropdown ">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Menu
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li>
              <%= link_to 'Trips', trips_path, class: 'btn btn-m' %>
              </li>
              <li>
              <%= link_to 'Cars', cars_path, class: 'btn btn-m' %>
              </li>
              <li>
              <%= link_to 'Users', users_path, class: 'btn btn-m' %>
              </li>
            </ul>
          </li>
        </ul>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>FleetRider</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link crossorigin="anonymous" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" rel="stylesheet">
  </head>

  <body>
    <%= render partial: 'layouts/header'%>

    <%= yield %>

    <% flash.each do |type, message| %>
    <div class="flash <%= type %>"><%= message %></div>
  <% end %>


  </body>

</html>

app/views/trips/_trips_feedback.html.erb
<% if @trip.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@trip.errors.count, "error") %> prohibited this trip from being saved:</h2>
    <ul>
      <% @trip.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/trips/edit.html.erb
  <%= form_for @trip, html: { class: "form-horizontal container mt-5" }, data: { turbo_frame: :_top } do |form|%>

    <%= turbo_frame_tag "trips_feedback" do %>
      <%= render "trips_feedback" %>
    <% end %>

    <div class="form-group">
      <%= form.label :car_id, class: "control-label" %>
      <%= form.select :car_id, Car.all.map { |car| [car.brand + ' ' + car.model, car.id] }, {}, { class: "form-control" } %>
    </div>

    <div class="form-group">
      <%= form.label :from, class: "control-label" %>
      <%= form.text_field :from, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :to, class: "control-label" %>
      <%= form.text_field :to, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :pitstop, class: "control-label" %>
      <%= form.text_field :pitstop, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :distance, class: "control-label" %>
      <%= form.number_field :distance, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :date_beginning, class: "control-label" %>
      <%= form.date_select :date_beginning, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :date_end, class: "control-label" %>
      <%= form.date_select :date_end, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :user_id, "Traveller", class: "control-label" %>
      <%= form.select :user_id, User.all.map { |user| ["#{user.first_name} #{user.last_name}", user.id] }, { class: "form-control" } %>

    </div>

    <div class="form-group">
      <%= form.submit "Save", class: "btn btn-primary" %>
    </div>
  <% end %>
<%= link_to 'Back', trips_path, class: "btn btn-primary mt-3 m-2" %>

app/views/trips/index.html.erb
<div class="container mt-5">
  <%== pagy_nav @pagy %>
  <table class="table">
    <thead>
    <tr>
      <th>Car</th>
      <th>From</th>
      <th>To</th>
      <th>Pitstop</th>
      <th>Distance</th>
      <th>Date Beginning</th>
      <th>Traveller</th>
      <th>Actions</th>
    </tr>
    </thead>
    <tbody>
    <% @trips.each do |trip| %>
      <tr>
        <td><%= "#{trip.car.brand} #{trip.car.model}" %></td>
        <td><%= trip.from %></td>
        <td><%= trip.to %></td>
        <td><%= trip.pitstop %></td>
        <td><%= trip.distance %></td>
        <td><%= trip.date_beginning.strftime("%Y-%m-%d") %></td>
        <td><%= "#{trip.user.first_name} #{trip.user.last_name}" %></td>
        <td>
          <%= link_to 'Edit', edit_trip_path(trip.id), class: 'btn btn-primary btn-sm' %>
          <%= link_to 'Delete', trip_path(trip.id), data: { turbo_confirm: 'Are you sure?', turbo_method: :delete}, class: 'btn btn-danger btn-sm' %>
          <%= link_to 'Details', trip_path(trip.id), class: 'btn btn-info btn-sm' %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
<%= link_to 'Add Trip', new_trip_path, class: 'btn btn-info btn-sm' %>
</div>

app/views/trips/new.html.erb
<%= form_for @trip, html: { class: "form-horizontal container mt-5" }, data: { turbo_frame: :_top } do |form|%>

  <%= turbo_frame_tag "trips_feedback" do %>
    <%= render "trips_feedback" %>
  <% end %>

  <div class="form-group">
    <%= form.label :car_id, class: "control-label" %>
    <%= form.select :car_id, Car.all.map { |car| [car.brand + ' ' + car.model, car.id] }, {}, { class: "form-control" } %>
  </div>

  <div class="form-group">
    <%= form.label :from, class: "control-label" %>
    <%= form.text_field :from, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :to, class: "control-label" %>
    <%= form.text_field :to, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :pitstop, class: "control-label" %>
    <%= form.text_field :pitstop, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :distance, class: "control-label" %>
    <%= form.number_field :distance, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :date_beginning, class: "control-label" %>
    <%= form.date_select :date_beginning, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :date_end, class: "control-label" %>
    <%= form.date_select :date_end, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :user_id, "Traveller", class: "control-label" %>
    <%= form.select :user_id, User.all.map { |user| ["#{user.first_name} #{user.last_name}", user.id] }, { class: "form-control" } %>

  </div>

  <div class="form-group">
    <%= form.submit "Save", class: "btn btn-primary" %>
  </div>
<% end %>
<%= link_to 'Back', trips_path, class: "btn btn-primary mt-3 m-2" %>

app/views/trips/show.html.erb
<div class="container mt-3">
  <h1>Details of the trip</h1>
  <div class="card">
    <div class="card-body">
      <p><strong>Car:</strong> <%= "#{@trip.car.brand} #{@trip.car.model}" %></p>
      <p><strong>From:</strong> <%= @trip.from %></p>
      <p><strong>To:</strong> <%= @trip.to %></p>
      <p><strong>Pitstop:</strong> <%= @trip.pitstop %></p>
      <p><strong>Distance:</strong> <%= @trip.distance %> km</p>
      <p><strong>Date Beginning:</strong> <%= @trip.date_beginning.strftime("%d-%m-%Y") %></p>
      <p><strong>Date End:</strong> <%= @trip.date_end.strftime("%d-%m-%Y") %></p>
      <p><strong>Fuel Used:</strong> <%= @trip.distance*@trip.car.fuel_consumption/100 %> liters</p>
      <p><strong>Traveller:</strong> <%= @trip.user_id %></p>
      <p><strong>Created At:</strong> <%= @trip.created_at.strftime("%d-%m-%Y %H:%M") %></p>
    </div>
  </div>

  <%= link_to 'Back', trips_path, class: "btn btn-primary mt-3" %>
</div>

app/views/users/_users_feedback.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
    <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/edit.html.erb
<%= form_for @user, html: { class: "form-horizontal container mt-5" }, data: { turbo_frame: :_top } do |form|%>

  <%= turbo_frame_tag "users_feedback" do %>
    <%= render "users_feedback" %>
  <% end %>

  <div class="form-group">
    <%= form.label :email, class: "control-label" %>
    <%= form.email_field :email, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :password, class: "control-label" %>
    <%= form.password_field :password, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :first_name, class: "control-label" %>
    <%= form.text_field :first_name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :last_name, class: "control-label" %>
    <%= form.text_field :last_name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :role, class: "control-label" %>
    <%= form.select :role, User.roles.keys.map { |role| [role.humanize, role] }, {}, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.submit "Save", class: "btn btn-primary" %>
  </div>
<% end %>
<%= link_to 'Back', users_path, class: "btn btn-primary mt-3 m-2" %>

app/views/users/index.html.erb
<div class="container mt-5">
  <%== pagy_nav @pagy %>
  <table class="table">
    <thead>
    <tr>
      <th>First Name</th>
      <th>Last Name</th>
      <th>Email</th>
      <th>Role</th>
    </tr>
    </thead>
    <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.email %></td>
        <td><%= user.role %></td>
        <td>
          <%= link_to 'Edit', edit_user_path(user.id), class: 'btn btn-primary btn-sm' %>
          <%= link_to 'Delete', user_path(user.id), data: { turbo_confirm: 'Are you sure?', turbo_method: :delete}, class: 'btn btn-danger btn-sm' %>
          <%= link_to 'Details', user_path(user.id), class: 'btn btn-info btn-sm' %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
  <%= link_to 'Add User', new_user_path, class: 'btn btn-info btn-sm' %>
</div>

app/views/users/new.html.erb
<%= form_for @user, html: { class: "form-horizontal container mt-5" }, data: { turbo_frame: :_top } do |form|%>

  <%= turbo_frame_tag "users_feedback" do %>
    <%= render "users_feedback" %>
  <% end %>

  <div class="form-group">
    <%= form.label :email, class: "control-label" %>
    <%= form.email_field :email, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :password, class: "control-label" %>
    <%= form.password_field :password, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :first_name, class: "control-label" %>
    <%= form.text_field :first_name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :last_name, class: "control-label" %>
    <%= form.text_field :last_name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :role, class: "control-label" %>
    <%= form.select :role, User.roles.keys.map { |role| [role.humanize, role] }, {}, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.submit "Save", class: "btn btn-primary" %>
  </div>
<% end %>
<%= link_to 'Back', users_path, class: "btn btn-primary mt-3 m-2" %>

app/views/users/show.html.erb
<div class="container mt-3">
  <h1>Details of the user</h1>
  <div class="card">
    <div class="card-body">
      <p><strong>First Name:</strong> <%= @user.first_name %></p>
      <p><strong>Last Name:</strong> <%= @user.last_name %></p>
      <p><strong>email:</strong> <%= @user.email %></p>
      <p><strong>Role:</strong> <%= @user.role %></p>
    </div>
  </div>

  <%= link_to 'Back', users_path, class: "btn btn-primary mt-3" %>
</div>